version: '2'
services:

#  The Application
  web:
    image: 474801623431.dkr.ecr.ap-southeast-2.amazonaws.com/rivl2/web
    restart: always
    ports:
      - "80:80"
  app:
    image: 474801623431.dkr.ecr.ap-southeast-2.amazonaws.com/rivl2/app
    restart: always
    environment:
    - "APP_KEY="
    - "DB_CONNECTION=mysql"
    - "DB_DATABASE=rivl2"
    - "DB_HOST=db"
    - "DB_USERNAME=root"
    - "DB_PASSWORD="
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume:
