version: '2'
services:

  #  The Application
  web:
    image: rivl2-web:latest
    build:
      context: ./
      dockerfile: web.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
  app:
    image: rivl2-app:latest
    build:
      context: ./
      dockerfile: app.dev.dockerfile
    env_file: '.env'
    volumes:
      - ./:/var/www
      #- ./resources:/var/www/resources
      #- ./public:/var/www/public
      - node_modules:/var/www/node_modules
#      - vendor:/var/www/vendor
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: '.env.mysql'
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
  node_modules:
#  vendor: